### PR TITLE
Support paren mode

### PR DESCRIPTION
**Pull request by iamFIREcracker**
This implements the final plumbing required to expose 'paren' mode to users

* Implements `parinfer#ToggleParinbferMode()` -- the command was already there
* Updates `parinfer#process_form()` to use `g:vim_parinfer_mode` and call the right library function
* Updates the help file

### CODE REVIEW

**Comment by bhurlow** [comment]
@iamFIREcracker very cool! Question: do you find the paren mode useful? Do you map it to key command?

**Comment by iamFIREcracker** [comment]
> Question: do you find the paren mode useful?

Yes, especially when editing function names (you expect the list of arguments to shift to the right).  The problem is, it does not always work (sometimes arguments are properly indented, sometimes they are not), but I honestly did not feel brave enough to understand if it was a problem with the wiring code, or with the underlying parinfer lib.

> Do you map it to key command?

Not yet, for now I simply run `:ToggleParinferMode` when I need it.

Anyway, let me know if there is anything you want me to update, or if you are interested in getting this merged.

**Comment by bhurlow** [comment]
@iamFIREcracker one thing, I'm seriously considering switching this back to using the parinfer python or javascript implementation, which might resolve the issue you mentioned. As pure as it feels to have a viml implementation, it's so much slower than passing the region to subshell

**Comment by iamFIREcracker** [comment]
> one thing, I'm seriously considering switching this back to using the parinfer python or javascript implementation, which might resolve the issue you mentioned. As pure as it feels to have a viml implementation, it's so much slower than passing the region to subshell

I am looking forward to it; let me know if you need some help testing when you have something somewhat working.

**Pull request merged**
